### PR TITLE
Remove 100% height from `.scrollbar-container`

### PR DESCRIPTION
**Pull request by ggwzrd**
This PR fixes the issue #98

### CODE REVIEW

**Comment by ggwzrd** [comment]
@goldenyz I updated this PR as per the comments in issue #98

**Comment by goldenyz** [comment]
The order of the class names on the object itself does not matter. It is the order of the style rules in the style sheet that matters.

**Comment by ggwzrd** [comment]
@goldenyz absolutely not, the class ordering matters, try changing the order in the HTML and you will see it. We are experiencing many bugs because of it.

**Comment by trangcongthanh** [comment]
@giuliogallerini  Can you tell me the color?
```
.red {
color: red;
}
.blue {
color: blue;
}

<div class="red blue">Blue?</div>
<div class="blue red">Red?</div>
```

**Comment by goldenyz** [comment]
It will always be blue because it is defined after `red`

**Comment by trangcongthanh** [comment]
> It will always be blue because it is defined after `red`

Oh sry :( I want to mention @giuliogallerini

**Comment by goldenyz** [comment]
@trangcongthanh :)

**Comment by ggwzrd** [comment]
@trangcongthanh @goldenyz that's indeed correct. Although I am not noticing a double declaration of the styles in the dev tools. 

Screenshot 2020-04-01 at 18 59 03

even if I included only once the styles in my `index.html`

Screenshot 2020-04-01 at 19 01 41

**Pull request closed without merging**
