### PR TITLE
Added getContainer() method

### PR DESCRIPTION
**Pull request by pinebit**
#19

### CODE REVIEW

**Comment by goldenyz** [comment]
Thanks for the contribution. I have a better way to expose the container ref: [containerRef](https://github.com/goldenyz/react-perfect-scrollbar#containerref). See #23 for more details.

**Comment by pinebit** [comment]
@goldenyz I checked your solution, it will work for me. But maybe you have a potential bug there:
`containerRef: PropTypes.func,` should be `isRequired`, because you did not check if `this.props.containerRef` is null before calling it.

**Comment by goldenyz** [comment]
@pinebit It would not a issue because I have defined the defaultProps

**Comment by pinebit** [comment]
That's right. Thank you.

**Pull request closed without merging**
